pipeline {
    agent {
        docker {
            image 'maven:3-alpine' 
            args '-v /root/.m2:/root/.m2' 
        }
    }
    stages {
        stage('Build') { 
            steps {
                sh 'mvn -B -DskipTests clean package' 
            }
        }
    }
    post {
        always {
            cleanWs() // 清理工作空间
        }
        success {
            archiveArtifacts artifacts: 'target/*.jar' // 归档产物
        }
    }
}